### ISSUE TITLE
bot后台日志中显示chatgpt值正常返回，但无法推送至微信，显示脚本异常

### ISSUE THREAD

**Issue by Henxidou001** [htnanako/MovieBot_plugins#12]
<img width="932" alt="截屏2024-11-26 15 02 35" src="https://github.com/user-attachments/assets/e242b42c-2ab9-4ac4-b405-d8c41e8cdf48">

**Comment by Henxidou001** [comment]
希望大佬能帮帮忙解决，能捐助

**Comment by htnanako** [comment]
> 
> 
> <img width="932" alt="截屏2024-11-26 15 02 35" src="https://github.com/user-attachments/assets/e242b42c-2ab9-4ac4-b405-d8c41e8cdf48">
> 
> 
> 
> 

你的企微推送服务接口有问题

**Comment by htnanako** [comment]
3分钟回复，不上GitHub看信息，打1块钱赞赏是来侮辱人的？程序没有问题，你自己查吧，奉陪不起。

**Comment by htnanako** [comment]
信息不看 过一个小时来发这个赞赏 用来道德绑架？
![image](https://github.com/user-attachments/assets/f5f5c84f-530e-45df-9512-29f2051071f5)
1块钱已捐
![image](https://github.com/user-attachments/assets/c1d438fe-169a-4e84-bd7c-77401cfd9038)

**Comment by Henxidou001** [comment]
大佬我真不是这个意思啊

**Comment by Henxidou001** [comment]
我承诺的捐助也不是1块钱啊，只是希望能联系到您

**Comment by Henxidou001** [comment]
我在代码和编程上基本是小白，都靠大佬的多种教程才一步一步到这个地步
