### ISSUE TITLE
今天中午向您提出了个人在运用插件过程中出现的一些问题，因为我在新疆的原因，也不能长时间使用vpn，提出问题后遂关闭了

### ISSUE THREAD

**Issue by Henxidou001** [htnanako/MovieBot_plugins#13]
今天中午向您提出了个人在运用插件过程中出现的一些问题，因为我在新疆的原因，也不能长时间使用vpn，提出问题后遂关闭了。
期间我自己也在着手多方面寻求帮助，中途经过一个小时也未能解决。所以在moviebot中查看了赞赏码，攒了1元钱，并非有任何恶意，只是想尝试看能否联系到您！

**Comment by Henxidou001** [comment]
就在刚才，在群聊中尝试了最后一次努力，然而并无它法

**Comment by Henxidou001** [comment]
所以才登上GitHub，发现了您的回复，抱歉

**Comment by Henxidou001** [comment]
烦请您能在闲暇之余能远程帮我检查一下吗？

**Comment by htnanako** [comment]
![image](https://github.com/user-attachments/assets/8639c9cf-f7dc-4e57-8986-38cfd3678691)
除了日志之外，你的自查呢？配置截图呢？

**Comment by Henxidou001** [comment]
方便加微信，您帮忙远程看一下吗

**Comment by Henxidou001** [comment]
dz0204这是我微信号，麻烦了

**Comment by htnanako** [comment]
> 方便加微信，您帮忙远程看一下吗

不方便

**Comment by Henxidou001** [comment]
todesk方便吗？

**Comment by Henxidou001** [comment]
<img width="547" alt="截屏2024-11-26 17 38 08" src="https://github.com/user-attachments/assets/a27616cd-6476-4fd5-9854-ef1bf3332af8">
<img width="548" alt="截屏2024-11-26 17 38 16" src="https://github.com/user-attachments/assets/061a3213-8cf1-4f2a-8be4-d3c1e9736a5c">
<img width="1476" alt="截屏2024-11-26 17 38 45" src="https://github.com/user-attachments/assets/0eecfb17-56f9-4c9b-9436-b93c4cefb71d">
moviebot配置的企业微信消息也都能正常回复，容器未挂代理、插件位挂代理（2者挂不挂代理都已经尝试过了）
国外gpt4接口也能正常在日志中返回信息

**Comment by Henxidou001** [comment]
<img width="699" alt="截屏2024-11-26 17 42 23" src="https://github.com/user-attachments/assets/b3922585-feeb-4ada-affa-c61d886b7baa">

**Comment by htnanako** [comment]
![image](https://github.com/user-attachments/assets/e399c54f-5287-4306-ac9c-29f403e42fad)
自己乱填

**Comment by Henxidou001** [comment]
应该怎么填啊

**Comment by Henxidou001** [comment]
https://qyapi.weixin.qq.com？？？

**Comment by htnanako** [comment]
自己去找教程 什么叫企业微信的推送api地址  主程序通知配置会写 插件同样的配置就乱写

**Comment by htnanako** [comment]
配置项该有的标题/副标题说明写得清清楚楚 主程序都能配起来用 一模一样的配置信息一模一样的标题/副标题 自以为是随便乱填

**Comment by Henxidou001** [comment]
好的，我去重新学一下

**Comment by Henxidou001** [comment]
解决了，谢谢作者
