### ISSUE TITLE
插件ChatGPT设置的企业微信消息API 一直openapi回调地址请求不通过

### ISSUE THREAD

**Issue by gaoshuoyi** [htnanako/MovieBot_plugins#8]
http://公网IP:1329/api/plugins/qywx_chatbot/chat 使用的是这个接受消息服务器
1329是MOVIE ROBOT的端口，
直接浏览器输入http://公网IP:1329/api/plugins/qywx_chatbot/chat，收到的是{"code": 1, "message": "请登陆后使用此功能！", "data": null}
Token和EncodingAESKey都已经配置在插件里面，使用的单独一个应有，和MR的微信通道分开了得！用MR的消息服务器地址是对的，但是用(http://公网IP:1329/api/plugins/qywx_chatbot/chat 就一直显示openapi回调地址请求不通过。不知道是哪里出了问题，是端口问题吗？没看到插件单独配置的端口啊？请大大指导下！
![image](https://github.com/htnanako/MovieBot_plugins/assets/166355876/989719b5-89a2-4629-9218-d154d5bfe711)
![image](https://github.com/htnanako/MovieBot_plugins/assets/166355876/b1e42a86-905a-405a-83d9-16089383e37b)

**Comment by htnanako** [comment]
> [http://公网IP:1329/api/plugins/qywx_chatbot/chat](http://%E5%85%AC%E7%BD%91IP:1329/api/plugins/qywx_chatbot/chat) 使用的是这个接受消息服务器 1329是MOVIE ROBOT的端口， 直接浏览器输入[http://公网IP:1329/api/plugins/qywx_chatbot/chat，收到的是{"code](http://%E5%85%AC%E7%BD%91IP:1329/api/plugins/qywx_chatbot/chat%EF%BC%8C%E6%94%B6%E5%88%B0%E7%9A%84%E6%98%AF%7B%22code)": 1, "message": "请登陆后使用此功能！", "data": null} Token和EncodingAESKey都已经配置在插件里面，使用的单独一个应有，和MR的微信通道分开了得！用MR的消息服务器地址是对的，但是用([http://公网IP:1329/api/plugins/qywx_chatbot/chat](http://%E5%85%AC%E7%BD%91IP:1329/api/plugins/qywx_chatbot/chat) 就一直显示openapi回调地址请求不通过。不知道是哪里出了问题，是端口问题吗？没看到插件单独配置的端口啊？请大大指导下！ ![image](https://private-user-images.githubusercontent.com/166355876/320348156-989719b5-89a2-4629-9218-d154d5bfe711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzE4ODQsIm5iZiI6MTcxMjU3MTU4NCwicGF0aCI6Ii8xNjYzNTU4NzYvMzIwMzQ4MTU2LTk4OTcxOWI1LTg5YTItNDYyOS05MjE4LWQxNTRkNWJmZTcxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxMDE5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjExMWMzNzViNWE5YzFiZWIwNDczOGQxOTlhYmRmNmJlYjY1ZTUyYzU0MjQ3OWY3ODEzYTJlYzk3YmIxNzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9L8qx6o1FhNN9h9mjVOT2clbO2gVBIiGO_ryhPbT46g) ![image](https://private-user-images.githubusercontent.com/166355876/320348236-b1e42a86-905a-405a-83d9-16089383e37b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzE4ODQsIm5iZiI6MTcxMjU3MTU4NCwicGF0aCI6Ii8xNjYzNTU4NzYvMzIwMzQ4MjM2LWIxZTQyYTg2LTkwNWEtNDA1YS04M2Q5LTE2MDg5MzgzZTM3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxMDE5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzNiOTA3OGM5YmVkMjRjMGM5ODcxYzBjZTg4MTM0ZTMyMDZmMTY1NDZjZjg2M2Q4MTUyYWEzMjA4YWY4MzQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9r7TZlUWdaCpUOofLNAOZOHDEyywTJAZ6VYiVRe4acE)

你这填的是啥啊 47这个IP是什么？

> [http://公网IP:1329/api/plugins/qywx_chatbot/chat](http://%E5%85%AC%E7%BD%91IP:1329/api/plugins/qywx_chatbot/chat) 使用的是这个接受消息服务器 1329是MOVIE ROBOT的端口， 直接浏览器输入[http://公网IP:1329/api/plugins/qywx_chatbot/chat，收到的是{"code](http://%E5%85%AC%E7%BD%91IP:1329/api/plugins/qywx_chatbot/chat%EF%BC%8C%E6%94%B6%E5%88%B0%E7%9A%84%E6%98%AF%7B%22code)": 1, "message": "请登陆后使用此功能！", "data": null} Token和EncodingAESKey都已经配置在插件里面，使用的单独一个应有，和MR的微信通道分开了得！用MR的消息服务器地址是对的，但是用([http://公网IP:1329/api/plugins/qywx_chatbot/chat](http://%E5%85%AC%E7%BD%91IP:1329/api/plugins/qywx_chatbot/chat) 就一直显示openapi回调地址请求不通过。不知道是哪里出了问题，是端口问题吗？没看到插件单独配置的端口啊？请大大指导下！ ![image](https://private-user-images.githubusercontent.com/166355876/320348156-989719b5-89a2-4629-9218-d154d5bfe711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzIxMzksIm5iZiI6MTcxMjU3MTgzOSwicGF0aCI6Ii8xNjYzNTU4NzYvMzIwMzQ4MTU2LTk4OTcxOWI1LTg5YTItNDYyOS05MjE4LWQxNTRkNWJmZTcxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxMDIzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmFmZThhOGI1ZmMwY2JiNGVkOWEzMDc5MWE1OTk1MjAzOTFhNTRkNGVhYzRiNzFlMzc0NTYyOWIxNjY1ZDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jHn_w3oobwRoTuvw5Kb1wxMUorxmHl7f4UI6hx8mE_c) ![image](https://private-user-images.githubusercontent.com/166355876/320348236-b1e42a86-905a-405a-83d9-16089383e37b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzIxMzksIm5iZiI6MTcxMjU3MTgzOSwicGF0aCI6Ii8xNjYzNTU4NzYvMzIwMzQ4MjM2LWIxZTQyYTg2LTkwNWEtNDA1YS04M2Q5LTE2MDg5MzgzZTM3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxMDIzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2E5NjRmNjI3MDRmMGJkOWIzMmE2YzFhZDA0MGFmYTZhZjJlMGVjN2YwZDY4NTFjMTExYmFkMWJlM2NmYzcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mKbIna_u8cWLWxSSbZXdqC6mpNHeyppGPx0uWf9em8o)

你这填的是啥啊 47这个IP是什么？

**Comment by gaoshuoyi** [comment]
47这个就是我的VPS的公网IP啊~

**Comment by htnanako** [comment]
> 47这个就是我的VPS的公网IP啊~

那你推送API地址填本机IP做什么呢？
另外 插件配置填完信息 保存后重启了没？企微后台接收信息服务器配置点保存，日志提示了什么？

**Comment by gaoshuoyi** [comment]
> > 47这个就是我的VPS的公网IP啊~
> 
> 那你推送API地址填本机IP做什么呢？ 另外 插件配置填完信息 保存后重启了没？企微后台接收信息服务器配置点保存，日志提示了什么？

说的对~我还没重启~我企业微信是对的~这个本机IP就是我的VPS代理啊~我MR的企业微信都是这么设置的~没有问题，我先去重启下看看

**Comment by gaoshuoyi** [comment]
重启了MR就对了~感谢大佬！
