### ISSUE TITLE
麻烦问一下短剧刮削 这个大概是是什么问题 

### ISSUE THREAD

**Issue by sexyfeifan** [htnanako/MovieBot_plugins#9]
![CleanShot 2024-05-05 at 12 26 12@2x](https://github.com/htnanako/MovieBot_plugins/assets/36148825/c5417879-73e4-4f32-8507-cc252cb7e90e)
![CleanShot 2024-05-05 at 12 26 49@2x](https://github.com/htnanako/MovieBot_plugins/assets/36148825/5d42dfc1-42fa-461a-9a74-02ff1f0f3fab)
![CleanShot 2024-05-05 at 12 27 10@2x](https://github.com/htnanako/MovieBot_plugins/assets/36148825/2d7b4ca2-931b-4679-aa88-532a5ea80e1a)
麻烦问一下短剧刮削 这个大概是是什么问题

**Comment by htnanako** [comment]
> ![CleanShot 2024-05-05 at 12 26 12@2x](https://private-user-images.githubusercontent.com/36148825/327989273-c5417879-73e4-4f32-8507-cc252cb7e90e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4OTA1NDksIm5iZiI6MTcxNDg5MDI0OSwicGF0aCI6Ii8zNjE0ODgyNS8zMjc5ODkyNzMtYzU0MTc4NzktNzNlNC00ZjMyLTg1MDctY2MyNTJjYjdlOTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDA2MjQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMGM0NTVkMzAwMmZlNmQ1OTE2NmRhY2QyNGMzZDE5OGEzNzk2ZDczYmU3MjQxMmEwOGEzODFhMGE3OGNmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gY-9GljtIWnear6eg_T8vEu4OKWXAWxxCrSqso7vfnI) ![CleanShot 2024-05-05 at 12 26 49@2x](https://private-user-images.githubusercontent.com/36148825/327989288-5d42dfc1-42fa-461a-9a74-02ff1f0f3fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4OTA1NDksIm5iZiI6MTcxNDg5MDI0OSwicGF0aCI6Ii8zNjE0ODgyNS8zMjc5ODkyODgtNWQ0MmRmYzEtNDJmYS00NjFhLTlhNzQtMDJmZjFmMGYzZmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDA2MjQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkODc0YjljMDgzNzA2OGY4ZDZiMmJlMDQ2ODE1OTAyMjNiNjU5ZjE3ZmIwYTM1ZGExMGIwYWQxMmIyYjliMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YLFNGnmbkv86CkM8RCsFvufswyeCPTR7K5fHlzaDnIU) ![CleanShot 2024-05-05 at 12 27 10@2x](https://private-user-images.githubusercontent.com/36148825/327989301-2d7b4ca2-931b-4679-aa88-532a5ea80e1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4OTA1NDksIm5iZiI6MTcxNDg5MDI0OSwicGF0aCI6Ii8zNjE0ODgyNS8zMjc5ODkzMDEtMmQ3YjRjYTItOTMxYi00Njc5LWFhODgtNTMyYTVlYTgwZTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDA2MjQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMDk1NmFjYTUyNGRmMmQwYmE1MGFiZTlkYjNmNzAwMWMwNzlhOTVjZjZkMjVkYTE1OGE0NDFmMmU5ZjBlYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xFKpOjo2p0aLbbkRR5D8IKa1vLuhOZTUzsELP8mJHF0) 麻烦问一下短剧刮削 这个大概是是什么问题

你执行手动命令 输入路径 为什么要输入两个路径用冒号隔开？

**Comment by sexyfeifan** [comment]
那条执行是我剪贴板没复制成功新的复制内容粘贴错了，后来执行的 /media/MovieBot/downloads/playlet 这个路径出现了日志里的这个错误

**Comment by htnanako** [comment]
> 那条执行是我剪贴板没复制成功新的复制内容粘贴错了，后来执行的 /media/MovieBot/downloads/playlet 这个路径出现了日志里的这个错误

视频文件夹和视频文件名发出来

**Comment by sexyfeifan** [comment]
![CleanShot 2024-05-05 at 21 24 51@2x](https://github.com/htnanako/MovieBot_plugins/assets/36148825/f32bb3cc-e393-478f-b551-afa96b4d8a90)
![CleanShot 2024-05-05 at 21 25 12@2x](https://github.com/htnanako/MovieBot_plugins/assets/36148825/08d1be56-f044-4f06-ae38-4c25307dd8c7)

**Comment by htnanako** [comment]
> ![CleanShot 2024-05-05 at 21 24 51@2x](https://github.com/htnanako/MovieBot_plugins/assets/36148825/f32bb3cc-e393-478f-b551-afa96b4d8a90)
> 
> ![CleanShot 2024-05-05 at 21 25 12@2x](https://github.com/htnanako/MovieBot_plugins/assets/36148825/08d1be56-f044-4f06-ae38-4c25307dd8c7)
> 
> 

这命名刮个啥啊

**Comment by sexyfeifan** [comment]
应该要什么样 名字加年份么？

**Comment by htnanako** [comment]
> 应该要什么样 名字加年份么？

pt站规范化命名
